// ═══════════════════════════════════════════════════════════════════════════════
// SCAN PATTERNS + ENGINE — shared between ReviewPolishTab and sub-components
// ═══════════════════════════════════════════════════════════════════════════════

export const SCAN_CATEGORIES = {
  instruction_leak: { label: "Instruction Leaks", icon: "🚨", weight: 25, color: "red" },
  duplicate_paragraph: { label: "Duplicate Paragraphs", icon: "🔂", weight: 30, color: "red" },
  tense_drift: { label: "Tense Drift", icon: "⏱", weight: 15, color: "red" },
  interiority_repetition: { label: "Interiority Repetition", icon: "🔁", weight: 10, color: "amber" },
  transition_crutch: { label: "Transition Crutches", icon: "🔗", weight: 8, color: "amber" },
  sensory_opener: { label: "Sensory Opener Monotony", icon: "👁", weight: 8, color: "amber" },
  scaffolding: { label: "Placeholder Scaffolding", icon: "🏗", weight: 10, color: "amber" },
  fiction_cliche: { label: "Fiction Clichés", icon: "📝", weight: 5, color: "blue" },
  hedging: { label: "Hedging Fog", icon: "🌫", weight: 5, color: "blue" },
  recap_bloat: { label: "Recap Bloat", icon: "♻️", weight: 5, color: "blue" },
  generic_conclusion: { label: "Generic Conclusions", icon: "🔚", weight: 5, color: "blue" },
  word_count: { label: "Word Count Issues", icon: "📏", weight: 4, color: "blue" },
  nf_fiction_trap: { label: "NF Crutch / Fiction Trap", icon: "📖", weight: 10, color: "amber" },
  nf_thesis_ending: { label: "NF Thesis Restatement", icon: "🔄", weight: 5, color: "amber" },
  nf_padding: { label: "NF Repetitive Padding", icon: "📋", weight: 8, color: "amber" },
  nf_unlabeled_reconstruction: { label: "NF Unlabeled Reconstruction", icon: "🎭", weight: 12, color: "red" },
  nf_polish: { label: "NF Polish Target", icon: "✨", weight: 5, color: "blue" },
  gemini_nf_cap: { label: "NF Frequency Cap", icon: "🔢", weight: 5, color: "amber" },
  gemini_nf_ban: { label: "NF Banned Phrase", icon: "🚫", weight: 10, color: "red" },
  gemini_nf_manuscript_cap: { label: "NF Manuscript Cap", icon: "📊", weight: 5, color: "amber" },
  nf_banned_phrase: { label: "NF Banned Phrase Caps", icon: "⛔", weight: 10, color: "red" },
  nf_manuscript_cap: { label: "NF Manuscript-Wide Caps", icon: "📊", weight: 8, color: "amber" },
  repetitive_padding: { label: "Repetitive Padding", icon: "🔄", weight: 12, color: "amber" },
  coffee_scene: { label: "Coffee Scene", icon: "☕", weight: 8, color: "amber" },
  archive_framing: { label: "Archive Framing", icon: "📁", weight: 8, color: "amber" },
};

export const PATTERNS = {
  instruction_leak: [
    [/\bAdjust the (year|name|time|date|setting|location|chapter) to (be |match |reflect )/gi, "Adjust the [X] to..."],
    [/\bRewrite to (focus|include|show|address|reflect|incorporate|emphasize)/gi, "Rewrite to..."],
    [/\bAddress the .{1,40}(incident|event|scene|cliffhanger|plot point) from the previous/gi, "Address the [X] from previous"],
    [/\b(consistent|inconsistent) with the (established |)?(timeline|outline|beat sheet|story bible)/gi, "consistent with the timeline"],
    [/\blike an anchor to this moment/gi, "like an anchor to this moment"],
    [/\badd a clear time transition/gi, "add a clear time transition"],
    [/\bchapter break indicator/gi, "chapter break indicator"],
    [/complete the (chapter|scene|story|section) or indicate/gi, "complete the chapter or indicate"],
    [/indicate if this is intentional/gi, "indicate if this is intentional"],
    [/should (I|we) (continue|complete|finish|expand)/gi, "should I continue/complete"],
    [/\[NOTE TO (AUTHOR|EDITOR|AI|SELF)\b/gi, "[NOTE TO AUTHOR/AI]"],
    [/\[TODO[:\s]/gi, "[TODO]"],
    [/as (instructed|requested|specified) (in|by) the (prompt|system|user)/gi, "as instructed by the prompt"],
    [/per the (outline|beat sheet|specification)/gi, "per the outline/beat sheet"],
    [/\bRemove specific \w+ or (cite|provide|anchor|source|use)/gi, "NF leak: Remove specific X or cite/provide..."],
    [/\bRemove (atmospheric|invented|fictional|fabricated) (reconstruction|detail|scene|quote)/gi, "NF leak: Remove atmospheric/invented..."],
    [/\bEither (identify|cite|name|source|provide|use) (the |a )?(specific|actual|real|documentary|documented)/gi, "NF leak: Either cite/provide specific..."],
    [/\bProvide (documentary|specific|archival|real) (source|evidence|documentation)/gi, "NF leak: Provide documentary source..."],
    [/\bReplace with documented (examples?|case stud|evidence|facts)/gi, "NF leak: Replace with documented..."],
    [/\bUse general (timeframe|terms?|reference|description|language)/gi, "NF leak: Use general timeframe..."],
    [/\bUse documented (examples?|case stud|evidence|sources)/gi, "NF leak: Use documented examples..."],
    [/\bLabel as (representative|illustrative|composite|general|reconstructed)/gi, "NF leak: Label as composite..."],
    [/\bFrame as (hypothetical|composite|reconstructed|general|illustrative)/gi, "NF leak: Frame as hypothetical..."],
    [/\bAnchor (to|these|this) (documented|real|specific|actual|verifiable)/gi, "NF leak: Anchor to documented..."],
    [/\bSource (to|this to) (actual|specific|documented|real)/gi, "NF leak: Source to actual..."],
    [/\bCite (specific|actual) (memoir|interview|archive|document|source|published)/gi, "NF leak: Cite specific source..."],
    [/\bVerify and cite\b/gi, "NF leak: Verify and cite..."],
    [/\bInsert documented\b/gi, "NF leak: Insert documented..."],
    [/\bor (clearly |)label as (representative|composite|illustrative|reconstructed|atmospheric|hypothetical)/gi, "NF leak: or label as composite..."],
    [/\bor (remove|begin with|provide|cite|frame|preface).{1,40}(fictional|documented|general|representative|composite|atmospheric|reconstructed|hypothetical)/gi, "NF leak: or remove/cite fictional..."],
    [/\bContemporary accounts (describe|suggest) similar [^.!?\n]{5,}/gi, "NF leak: meta-framing instruction"],
    [/\bUse '([^']+)' or [^.!?\n]{5,}/gi, "NF leak: Use quoted example or..."],
    [/\b(Remove specific|Use general|Either provide|Either cite|Either use) \w+(\s\w+)? or (cite|provide|use|anchor|source|reference) \w/gi, "NF leak: fused instruction-prose"],
  ],
  tense_past_drift: [
    [/\b(he|she|they|it|I|we)\s+(walks|runs|says|thinks|feels|knows|sees|hears|stands|sits|looks|moves|turns|opens|closes|steps|reaches|pulls|pushes|watches|presses|asks|cuts|fills|takes|sets|picks|drops|begins|starts|stops|grabs|holds|catches|lifts|places)\b/gi, "present-tense verb in past-tense narrative"],
  ],
  tense_present_drift: [
    [/\b(he|she|they|it|I|we)\s+(walked|ran|said|thought|felt|knew|saw|heard|stood|sat|looked|moved|turned|opened|closed|stepped|reached|pulled|pushed|watched|pressed|asked|cut|filled|took|set|picked|dropped|began|started|stopped|grabbed|held|caught|lifted|placed)\b/gi, "past-tense verb in present-tense narrative"],
  ],
  interiority_repetition: [
    [/\bhollow\b/gi, "hollow", 2], [/\bhollowness\b/gi, "hollowness", 1],
    [/\bempty\b/gi, "empty", 3], [/\bemptiness\b/gi, "emptiness", 2],
    [/\bshattered\b/gi, "shattered", 2], [/\bbroken\b/gi, "broken", 3],
    [/\bnumb(ness)?\b/gi, "numb/numbness", 2], [/\bvoid\b/gi, "void", 2],
    [/\baching?\b/gi, "ache/aching", 4], [/\bfragile\b/gi, "fragile", 3],
  ],
  transition_crutch: [
    [/\bFurthermore\b/g, "Furthermore"], [/\bMoreover\b/g, "Moreover"],
    [/\bIn addition\b/gi, "In addition"], [/\bAdditionally\b/g, "Additionally"],
    [/\bIt'?s worth noting that\b/gi, "It's worth