import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const prompts = [
      { title: "Arkham Academic Investigations: Miskatonic Cuneiform Mystery", description: "A skeptical professor at Miskatonic must decipher a cuneiform tablet linked to the Necronomicon.", content: "Create a Lovecraftian horror gamebook set at Miskatonic University in 1926, centering on a skeptical professor of ancient languages forced to decipher a cuneiform tablet linked to the Necronomicon.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Mystery", "Academic"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Missing Faculty Mystery", description: "An anthropology student investigates mysterious faculty disappearances at Miskatonic.", content: "Develop an interactive horror gamebook where a third-year anthropology student at Miskatonic investigates mysterious faculty disappearances tied to pre-human civilization research.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Mystery"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Orne Library Corruption", description: "A librarian discovers a corrupted micrograph plate with strange photographic anomalies.", content: "Generate a horror gamebook in the Orne Library archives where a junior librarian discovers corrupted micrograph plates with anomalous images.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Archives"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Antarctic Expedition Inconsistencies", description: "A journalist uncovers inconsistencies in Antarctic expedition letters revealing spectral visitations.", content: "Write a Lovecraftian horror gamebook set in 1925 where a journalist uncovers inconsistencies in Miskatonic's Antarctic expedition letters.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Expedition"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Dream Diary Obsession", description: "A neuropsychologist becomes obsessed with a student's dream diary mentioning hollow scholars.", content: "Create a cosmic horror gamebook about a neuropsychologist obsessed with dream diaries mentioning hollow scholars beneath College Hill.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Dreams"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Medical College Autopsy", description: "A pathologist discovers strange symbols inside a professor's body during autopsy.", content: "Write a gamebook set in Arkham's medical college where a pathologist discovers strange symbols inside a dead professor.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Medical"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Genealogy and The Rats in the Walls", description: "An archivist discovers breeding patterns in a genealogy text linked to The Rats in the Walls.", content: "Create an interactive gamebook in 1930s Arkham where an archivist discovers breeding patterns implicating university faculty.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Archives"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Occult Sermon Translation", description: "A theology student translates rare occult sermons suppressed since Salem witch trials.", content: "Generate a gamebook where a theology student translates occult sermons from Salem witch trials.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Arkham", "Horror", "Religious"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Pnakotic Manuscript Authentication", description: "A doctoral candidate attempts to verify an original Pnakotic Manuscript copy.", content: "Write an investigation gamebook about authenticating a Pnakotic Manuscript found in a fraternity safe.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Mystery"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Janitor's Discovery", description: "A janitor encounters tomes beyond human comprehension during maintenance.", content: "Create a cosmic horror gamebook from a janitor's perspective discovering forbidden books.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Cosmic"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Sumerian Whispers", description: "A professor receives whispered Sumerian phrases from students who remember nothing.", content: "Compose a gamebook where a linguistics professor receives Sumerian whispers from students.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Arkham", "Horror", "Linguistic"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Philosophy Reality Shift", description: "A philosophy professor questions Lovecraftian folklore as reality shifts.", content: "Develop a gamebook where a skeptical philosopher's investigation causes reality distortions.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Philosophical"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Chess Society Time Alteration", description: "A faculty member joins an esoteric chess society where matches alter time.", content: "Generate a gamebook about the Miskatonic Chess Society where games manipulate time and memory.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Games"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Telescope Transmission Mystery", description: "An astronomy professor discovers telescope recordings with Whisperer in Darkness signals.", content: "Create a gamebook where an astronomer finds strange transmissions from old telescope domes.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Cosmic"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Ethnomusicology Wax Cylinders", description: "An assistant investigates obscure wax cylinders labeled Cthaegh's Choir.", content: "Write a gamebook investigating mysterious wax cylinder recordings with auditory hallucinations.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Audio"], word_count: 2800 },
      { title: "Arkham Academic Investigations: Faculty Dream Sleeper", description: "A historian uncovers a removed faculty member who only dreamed.", content: "Design a gamebook about uncovering a faculty member whose only function was dreaming.", book_type: "fiction", genre: "Horror", category: "Arkham Academic Investigations", tags: ["Miskatonic", "Horror", "Dreams"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Cataloging Error", description: "A student discovers a forbidden tome with no official registry.", content: "Create a gamebook set in the Restricted Archives where a cataloging error reveals a hidden forbidden book.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Mystery"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Professor's Death", description: "A faculty member cleans up after a professor found dead in the archives.", content: "Write a gamebook about cleaning up a dead professor's effects in the Restricted Archives.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Death"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Grimoire Restoration", description: "A conservator restores water-damaged grimoires where strange words appear.", content: "Generate a gamebook where restoring grimoires reveals words that shouldn't exist.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Books"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Vatican Crates Translation", description: "A scholar assists in translating sealed Vatican crates marked Adversus Necrologia.", content: "Design a gamebook about translating mysterious Vatican crates from 1923.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Religious"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Clay Tablets Discovery", description: "An archivist discovers clay tablets listed as replicas are actually authentic.", content: "Create a gamebook where clay tablets prove to be authentic with cultic lineage.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Archaeological"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Night Watchman Strange Behavior", description: "A nightwatchman records strange behavior after new archaeological shipments.", content: "Write a gamebook about a watchman documenting strange phenomena in the lower archives.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Supernatural"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Fire and Hidden Text", description: "A science instructor finds a 17th-century medical text after a fire.", content: "Develop a gamebook where a fire reveals hidden 17th-century medical texts.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Medical"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Brine and Dead Moths", description: "Alumni donations to archives begin leaking brine and dead moths.", content: "Generate a gamebook about mysterious donations leaking brine and death.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Mystery"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: War Veteran Groundskeeper", description: "A war veteran discovers miscatalogued items predating the university.", content: "Write a gamebook where a veteran groundskeeper finds documents predating Miskatonic.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Time"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Pickman Etchings Discovery", description: "An art historian analyzes undocumented Richard Pickman etchings.", content: "Generate a gamebook about analyzing Pickman etchings showing impossible archive angles.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Art"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: Dreams and Falling Shelves", description: "A janitor survives collapse and discovers dreams influenced by manuscripts.", content: "Create a gamebook about a janitor whose dreams are influenced by unopened books.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Dreams"], word_count: 2800 },
      { title: "Miskatonic University Restricted Archives: South Pacific Artifacts", description: "An anthropologist documents artifacts from The Call of Cthulhu.", content: "Write a gamebook set in 1920 documenting South Pacific artifacts linked to Cthulhu.", book_type: "fiction", genre: "Horror", category: "Miskatonic University Restricted Archives", tags: ["Archives", "Horror", "Cthulhu"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Marsh Family Catalog", description: "An antiquarian catalogs Marsh family belongings, uncovering Deep One evidence.", content: "Design a gamebook where cataloging Marsh family items reveals Deep One pact evidence.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Deep Ones"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Asylum Patient Interviews", description: "A psychiatrist interviews Innsmouth survivors in a remote asylum.", content: "Create a gamebook where interviewing asylum patients reveals Deep One influence.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Asylum"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Naval Intelligence Deep One Activity", description: "A naval officer investigates resurfaced Deep One activity.", content: "Write a gamebook where naval intelligence uncovers resurfaced Deep One worship.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Military"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Marsh Family Influence Genealogy", description: "A folklorist retraces Marsh family influence revealing hidden shrines.", content: "Generate a gamebook where tracing genealogy reveals Innsmouth's far reach.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Genealogy"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Coastal Map Inconsistencies", description: "A cartographer discovers warped coastal maps and submerged cities.", content: "Create a gamebook where mapping anomalies reveal returning submerged cities.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Maps"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Boarding School Children", description: "A teacher uncovers hidden journals among Innsmouth survivor children.", content: "Write a gamebook where teacher discovers Innsmouth children's ritual journals.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Children"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Sunken Harbor Salvage", description: "A diver explores Innsmouth Harbor discovering Dagon artifacts.", content: "Generate a gamebook about diving Innsmouth Harbor's disturbing depths.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Diving"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Museum Artifact Acquisition", description: "A curator navigates ritual items from Innsmouth causing hauntings.", content: "Create a gamebook where museum artifacts trigger escalating paranormal events.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Museum"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Strange Births Investigation", description: "A journalist investigates anonymous tips about strange births in coastal towns.", content: "Write a gamebook investigating strange births and aquatic cult resurgence.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Cults"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Devil Reef Signals", description: "A Coast Guard sentry documents strange nocturnal signals from Devil Reef.", content: "Generate a gamebook about deciphering mysterious ocean signals.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Signals"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Escaped Resident Lineage", description: "A former Innsmouth resident returns to uncover family Deep One heritage.", content: "Create a gamebook where returning reveals terrible family lineage truths.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Family"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Miskatonic River Drownings", description: "A coroner investigates mysterious drownings with inhuman traits.", content: "Write a gamebook investigating drownings linked to exiled Innsmouth cultists.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Investigation"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Occult Text Recovery", description: "A professor recovers occult texts linked to the Esoteric Order of Dagon.", content: "Generate a gamebook about recovering forbidden Dagon cult texts.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Occult"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: Artist Colony Underwater Cities", description: "A painter discovers an artist colony founded by Innsmouth refugees.", content: "Create a gamebook where art colony founders prove to be Innsmouth survivors.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "Art"], word_count: 2800 },
      { title: "Innsmouth Aftermath Mysteries: FBI Agent Port Towns", description: "An ex-FBI agent sees familiar faces in port towns after Innsmouth raid.", content: "Write a gamebook where an FBI agent investigates Innsmouth survivors across America.", book_type: "fiction", genre: "Horror", category: "Innsmouth Aftermath Mysteries", tags: ["Innsmouth", "Horror", "FBI"], word_count: 2800 }
    ];

    const created = await base44.asServiceRole.entities.PromptCatalog.bulkCreate(prompts);
    return Response.json({ success: true, count: created.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});